name: Sync with Upstream 

on:
  workflow_dispatch: # Allow manual trigger
  
permissions:
  contents: write
  
jobs:
  upstream-sync:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your fork
      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        
      # Step 2: Add upstream repository
      - name: Add Upstream Repository
        run: |
          git remote add upstream https://github.com/epicweb-dev/epic-stack.git
          git fetch upstream

      # Step 3: Merge upstream changes
      - name: Merge Changes
        run: |
          git checkout main
          git merge upstream/main --no-edit || true

      # Step 4: Push merged changes back to your fork
      - name: Push Changes
        run: |
          git push origin main
